config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'questions#index'


  resources :questions do
    resources :answers, except: [:index, :show, :new]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers

	validates :title, presence: true
	validates :body, presence: true


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	before_action :authenticate_user!, only: [:create, :edit, :udpate, :destroy]


	def index
		@answers = Answer.all
	end

	def create
		@answer = Answer.new(answer_params)
		if @answer.save
			flash [:success] = "La respuesta ha sido guardada"
		end
		redirect_to question_path(params[:question_id])
	end

	def edit
	end

	def update
		if @answer.update(answer_params)
			flash [:success] = "La respuesta ha sido actualizada"
		end
		redirect_to question_path(params[:question_id])
	end

	def destroy
		@answer = Answer.find_by(question_id: params[:question_id], id: params[:id])
		if @answer.destroy
			flash [:success] = "La respuesta ha sido eliminada"
		end
		redirect_to question_path(params[:question_id])
	end

	private

	def answer_params
		params.require(:answer).permit(:body)
		.merge(user_id: current_user.id, question_id: params[:question_id])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :set_question, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :create, :edit,:update]

	def index
		@questions = Question.all.order(created_at: :desc).limit(10)
	end

	def show
		@answer = Answer.new
		@answers = @question.answers.all.order(created_at: :asc).limit(10)
	end

	def new
		@question = Question.new
	end

	def create
		@question = current_user.questions.new(question_params)
		if @question.save
			flash[:success]= "La pregunta ha sido creada"
			redirect_to questions_path
		else 
			render :new
		end
	end

	def update
		if @question.update(question_params)
			flash[:success] = "La pregunta ha sido actualizada"
			redirect_to questions_path
		else
			render :edit
		end
	end

	def destroy
		@question.destroy
		flash[:success] = 'La pregunta ha sido eliminada con éxito.'
		redirect_to questions_path
	end


	private


	def set_question
		@question = Question.find(params[:id])
	end

	def question_params
		params.require(:question).permit(:title, :body)
	end



end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div data-id="<% answer.id %>">
	<p><%=answer.body %></p>
	<div>
		<% if logged_in? && answer.user == current_user %>
			<%= link_to  " <span class='glyphicon glyphicon-pencil'></span> Editar"
			.html_safe,
			edit_question_answer_path(answer.question, answer) %> |
			<%= link_to " <span class='glyphicon glyphicon-trash'></span> Eliminar"
	        .html_safe, 
	        question_answer_path(answe.question, answer), method: :delete, 
	        data: {confirm: "Estás seguro?"} %>
	    <% end %>

	</div>

</div>

<br>

app/views/answers/_form.html.erb
<div class="col-md-12">
  <%= form_with model: answer, url: question_answers_path(question), local: true do |f| %>
    <%= render 'shared/error_messages', model: answer %>

    <div class="form-group">
      <%= f.label :body, "Nueva Respuesta:" %>
      <%= f.text_area :body, rows: 5, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit action, class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OverflowStacky</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container">
         <% flash.each do |message_type, message| %>
           <div class="alert alert-<%= message_type %> alert-dismissible" role="alert">
             <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
             <%= message %>
           </div>
         <% end %>

    <%= yield %>

    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1><%= title %></h1>
    <%= form_with model: question, local: true do |f| %>
      <%= render 'shared/error_messages', model: question %>

      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 10, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit action, class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<%= render 'form', question: @question, title: "Editar Pregunta", action: "Guardar" %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h1>Preguntas</h1>
    <% if user_signed_in? %>
      <p class="text-right">
        <%= link_to "Hacer una Pregunta", new_question_path, class: "btn btn-primary" %>
      </p>
    <% end %>
    <% @questions.each do |question| %>
      <div data-id="<%= question.id %>">
        <p><%= question.title %></p>
        <p><%= question.body %></p>
        <div>
          <%= link_to "<span class='glyphicon glyphicon-eye-open'></span> Ver"
            .html_safe,
            question %>
          <% if user_signed_in? && question.user == current_user %>
              | <%= link_to " <span class='glyphicon glyphicon-pencil'></span> Editar"
                  .html_safe,
                  edit_question_path(question) %>
              | <%= link_to " <span class='glyphicon glyphicon-trash'></span> Eliminar"
                  .html_safe, question,
                  method: :delete,
                  data: { confirm: "¿Estás seguro de eliminar esta pregunta?" } %>
          <% end %>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form', question: @question, title: "Publicar Pregunta", action: "Preguntar" %>

app/views/questions/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <h2>Pregunta <%= @question.id %></h2>
    <p><strong>Title: </strong><%= @question.title %></p>
    <p><strong>Body:</strong></p>
    <p><%= @question.body %></p>
    <div>
      <%= link_to "Editar", edit_question_path(@question) %> |
      <%= link_to "Volver", questions_path %>
    </div>

    <h3>Respuestas:</h3><br>
    <%= render 'answers/form', question: @question, answer: @answer, action: "Responder" %>

    <% @answers.each do |answer| %>
      <%= render 'answers/answer', answer: answer %>
    <% end %>

  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    The form contains <%= pluralize(model.errors.count, "error") %>:
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>